version: '3'

services:
  stripe:
    container_name: ignews-stripe-cli
    image: stripe/stripe-cli:latest
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
    command: listen --forward-to host.docker.internal:3000/api/webhooks
